const API='https://my-level-api.onrender.com';const WS='wss://my-level-api.onrender.com';const token=localStorage.getItem('myLevelAdminToken');const root=document.querySelector('#devices');const count=document.querySelector('#count'),online=document.querySelector('#online'),sharing=document.querySelector('#sharing');let socket=null;let selected=null;let reconnectTimer=null;let peer=null;let pendingCandidates=[];
function esc(v){return String(v).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]))}
function render(ds){count.textContent=ds.length;online.textContent=ds.filter(d=>d.status==='online').length;sharing.textContent=ds.filter(d=>d.sharing).length;if(!ds.length){root.innerHTML='<div class="empty"><strong>No computers connected</strong><span>Authorized computers will appear here after pairing.</span></div>';return}root.innerHTML=ds.map(d=>`<article class="device"><div class="device-main"><div class="device-icon">▣</div><div class="device-copy"><h3>${esc(d.name)}</h3><div class="meta"><span>${esc(d.platform)}</span><span class="meta-dot"></span><span>${d.sharing?'Screen sharing on':'Screen sharing off'}</span></div></div></div><div class="device-side"><span class="status ${d.status}">${d.status}</span><button class="view-button" data-id="${esc(d.id)}" ${d.status!=='online'||!d.sharing?'disabled':''}>View screen</button></div></article>`).join('');root.querySelectorAll('.view-button:not([disabled])').forEach(b=>b.onclick=()=>view(b.dataset.id))}
async function load(){if(!token){location.href='/admin-login.html';return}try{const r=await fetch(API+'/api/admin/devices',{headers:{Authorization:'Bearer '+token},cache:'no-store'});if(r.status===401){localStorage.removeItem('myLevelAdminToken');location.href='/admin-login.html';return}if(!r.ok)throw new Error('Backend request failed');render(await r.json())}catch(e){root.innerHTML='<div class="empty"><strong>Unable to load computers</strong><span>Refresh after the server finishes deploying.</span></div>'}}
function send(m){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify(m))}
function connect(){if(!token)return;if(socket?.readyState===WebSocket.OPEN||socket?.readyState===WebSocket.CONNECTING)return;socket=new WebSocket(WS);socket.onopen=()=>{send({type:'admin.connect',token});if(selected)setTimeout(()=>send({type:'admin.view',deviceId:selected}),100)};socket.onmessage=async e=>{if(typeof e.data!=='string')return;try{const m=JSON.parse(e.data);if(m.type==='devices'){render(m.devices)}else if(m.type==='webrtc.answer'){await handleAnswer(m)}else if(m.type==='webrtc.candidate'){await handleCandidate(m.candidate)}else if(m.type==='webrtc.error'){setViewerStatus(m.message);closePeer(false)}}catch(err){setViewerStatus('Viewer error: '+(err?.message||'unknown'))}};socket.onerror=()=>setViewerStatus('Viewer connection error. Reconnecting…');socket.onclose=()=>{if(selected)setViewerStatus('Viewer disconnected. Reconnecting…');clearTimeout(reconnectTimer);reconnectTimer=setTimeout(connect,1500)}}
async function startPeer(){closePeer(false);pendingCandidates=[];peer=new RTCPeerConnection({iceServers:[{urls:'stun:stun.cloudflare.com:3478'}]});peer.addTransceiver('video',{direction:'recvonly'});peer.ontrack=e=>{const video=document.querySelector('#screenVideo');if(video&&e.streams[0]){video.srcObject=e.streams[0];video.play().catch(()=>{});setViewerStatus('Connecting live video…')}};peer.onicecandidate=e=>{if(e.candidate)send({type:'webrtc.candidate',deviceId:selected,candidate:e.candidate.toJSON()})};peer.onconnectionstatechange=()=>{const s=peer?.connectionState;if(s==='connected')setViewerStatus('Live screen · WebRTC connected');else if(s==='failed')setViewerStatus('WebRTC connection failed.');else if(s==='disconnected')setViewerStatus('WebRTC disconnected…')};const offer=await peer.createOffer();await peer.setLocalDescription(offer);send({type:'admin.view',deviceId:selected});send({type:'webrtc.offer',deviceId:selected,sdp:offer.sdp})}
async function handleAnswer(m){if(!peer)return;await peer.setRemoteDescription({type:'answer',sdp:m.sdp});for(const c of pendingCandidates){try{await peer.addIceCandidate(c)}catch{}}pendingCandidates=[]}
async function handleCandidate(c){if(!peer||!c)return;if(peer.remoteDescription)try{await peer.addIceCandidate(c)}catch{}else pendingCandidates.push(c)}
function closePeer(notify=true){if(peer){try{peer.close()}catch{}}peer=null;pendingCandidates=[];if(notify)send({type:'admin.stop-view'})}
function setViewerStatus(text){const el=document.querySelector('#viewerStatus');if(el)el.textContent=text}
function view(id){selected=id;let modal=document.querySelector('#viewer');if(!modal){modal=document.createElement('div');modal.id='viewer';modal.innerHTML='<div style="position:fixed;inset:0;background:rgba(0,0,0,.92);z-index:9999;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:24px"><button id="closeViewer" style="align-self:flex-end;margin-bottom:12px;padding:10px 16px;border-radius:10px;border:0;cursor:pointer">Close</button><video id="screenVideo" autoplay playsinline muted style="max-width:95vw;max-height:85vh;object-fit:contain;background:#111;border-radius:10px"></video><div id="viewerStatus" style="color:white;margin-top:10px">Starting WebRTC live screen…</div></div>';document.body.appendChild(modal);document.querySelector('#closeViewer').onclick=()=>{closePeer(true);selected=null;modal.remove()}}setViewerStatus('Starting WebRTC live screen…');if(socket?.readyState===WebSocket.OPEN)startPeer();else connect()}
document.querySelector('#refresh').onclick=load;document.querySelector('#logout').onclick=()=>{closePeer(true);localStorage.removeItem('myLevelAdminToken');if(socket?.readyState===WebSocket.OPEN)socket.close();location.href='/'};load();connect();